[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build -w @vantum/shared && npm run build -w @vantum/backend"]

[start]
cmd = "node backend/dist/index.js"
